version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: backend
    environment:
      DATABASE_URL: "mysql://root:@mysql:3306/db?serverVersion=8.0&charset=utf8mb4"
      APP_ENV: dev
      APP_DEBUG: 1
      APP_SECRET: votre_secret_ici
      CORS_ALLOW_ORIGIN: '^https?://(localhost|127\.0\.0\.1)(:[0-9]+)?$'
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3001:3000"

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: ""  # Pas de mot de passe
      MYSQL_DATABASE: db        # Nom de la base
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf:ro
      - mysql_data:/var/lib/mysql
    ports:
      - "3307:3306"
    command:
      - --default-authentication-plugin=mysql_native_password
      - --ssl=OFF

volumes:
  mysql_data:
