api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        pagination_enabled: true
        pagination_items_per_page: 10 # Nombre d'éléments par page
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
    mapping:
        paths:
            - '%kernel.project_dir%/src/Entity' # Chemin pour les entités exposées
    formats:
        jsonld: ['application/ld+json']
        json: ['application/json']
        html: ['text/html']
    swagger:
        versions: [3] # Utiliser Swagger v3
    graphql:
        enabled: false # Active GraphQL si nécessaire
